.TH bsnes-plus-nwa 1 "23 Jun 2024" "version 0.05-nwa3"

.\" The name of the executable
.SH NAME
bsnes-plus-nwa - Fork of Bsnes-plus implementing the Emulator Network Access protocol

.\" This is how you start your program and if there is any additional option
.SH SYNOPSIS

bsnes-plus-nwa

.\" The complete description
.SH DESCRIPTION
Bnes-plus is a SNES emulator more focused on debugging. This fork implement the NWA protocol 

.\" Auhtor infos
.SH AUTHOR
Black Sliver <>
